from __future__ import annotations

from ..providers.base import ToolSpec
from .registry import ToolRegistry


SCAN_ROOT = ToolSpec(
    name="scan_root",
    description="Scan a REAPER project root directory for issues: nested projects, orphaned media, duplicates, regenerable files, external media, missing media. Returns summary counts.",
    parameters={
        "type": "object",
        "properties": {
            "path": {"type": "string", "description": "Absolute path to the project root directory to scan."},
        },
        "required": ["path"],
    },
    executor="local",
)

LIST_FINDINGS = ToolSpec(
    name="list_findings",
    description="List detailed findings from a scanned project root. Optionally filter by finding type.",
    parameters={
        "type": "object",
        "properties": {
            "root": {"type": "string", "description": "Project root path that was scanned."},
            "type": {"type": "string", "description": "Optional filter: nested_project, orphaned_media, regenerable, external_media, duplicate, missing_media."},
        },
        "required": ["root"],
    },
    executor="local",
)

GET_FILE_DETAILS = ToolSpec(
    name="get_file_details",
    description="Get detailed info about a file: size, modification date, hash, existence.",
    parameters={
        "type": "object",
        "properties": {
            "path": {"type": "string", "description": "Absolute path to the file."},
        },
        "required": ["path"],
    },
    executor="local",
)

LIST_QUARANTINE_BATCHES = ToolSpec(
    name="list_quarantine_batches",
    description="List past quarantine batches with date, file count, and total size.",
    parameters={"type": "object", "properties": {}, "required": []},
    executor="local",
)

QUARANTINE_FILES = ToolSpec(
    name="quarantine_files",
    description="Move files to a dated quarantine folder (reversible — files are NOT deleted). Requires confirmation.",
    parameters={
        "type": "object",
        "properties": {
            "paths": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Absolute paths to files to quarantine.",
            },
        },
        "required": ["paths"],
    },
    executor="local",
    destructive=True,
    return_confirmation=True,
)

RECLAIM_SPACE = ToolSpec(
    name="reclaim_space",
    description="Delete regenerable files (.reapeaks, .RPP-UNDO, *.RPP-bak). These are automatically regenerated by REAPER. Requires confirmation.",
    parameters={
        "type": "object",
        "properties": {
            "root": {"type": "string", "description": "Project root to scan. If omitted, uses all configured project roots."},
        },
        "required": [],
    },
    executor="local",
    destructive=True,
    return_confirmation=True,
)

CONSOLIDATE_PROJECT = ToolSpec(
    name="consolidate_project",
    description="Copy externally-referenced media files into the project directory. Does NOT modify the .RPP — save from REAPER with 'Copy media' checked. Requires confirmation.",
    parameters={
        "type": "object",
        "properties": {
            "project_path": {"type": "string", "description": "Path to the .RPP file to consolidate."},
        },
        "required": ["project_path"],
    },
    executor="local",
    destructive=True,
    return_confirmation=True,
)

UNNEST_PROJECT = ToolSpec(
    name="unnest_project",
    description="Copy a nested .RPP to its own top-level folder under projects_root. Original is left in place for verification. Requires confirmation.",
    parameters={
        "type": "object",
        "properties": {
            "project_path": {"type": "string", "description": "Path to the nested .RPP file."},
        },
        "required": ["project_path"],
    },
    executor="local",
    destructive=True,
    return_confirmation=True,
)

SET_PROJECTS_ROOT = ToolSpec(
    name="set_projects_root",
    description="Add a directory to the configured project roots for library scanning.",
    parameters={
        "type": "object",
        "properties": {
            "path": {"type": "string", "description": "Absolute path to add to projects_roots."},
        },
        "required": ["path"],
    },
    executor="local",
)


def build_library_registry() -> ToolRegistry:
    reg = ToolRegistry()
    for spec in [
        SCAN_ROOT, LIST_FINDINGS, GET_FILE_DETAILS,
        LIST_QUARANTINE_BATCHES, QUARANTINE_FILES, RECLAIM_SPACE,
        CONSOLIDATE_PROJECT, UNNEST_PROJECT, SET_PROJECTS_ROOT,
    ]:
        reg.register(spec)
    return reg
